namespace Qactive
{
  public enum QbservableProtocolMessageKind : byte
  {
    Unknown,
    OnNext,
    OnCompleted,
    OnError,
    Shutdown,
    Argument,
    Subscribe,
    DuplexInvoke,
    DuplexSubscribe,
    DuplexDisposeSubscription,
    DuplexGetEnumerator,
    DuplexGetEnumeratorResponse,
    DuplexGetEnumeratorErrorResponse,
    DuplexMoveNext,
    DuplexResetEnumerator,
    DuplexDisposeEnumerator,
    DuplexEnumeratorResponse,
    DuplexEnumeratorErrorResponse,
    DuplexResponse,
    DuplexErrorResponse,
    DuplexSubscribeResponse,
    DuplexOnNext,
    DuplexOnCompleted,
    DuplexOnError
  }
}