//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qactive.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qactive.Properties.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client rewritten expression.
        /// </summary>
        internal static string ClientRewrittenExpression {
            get {
                return ResourceManager.GetString("ClientRewrittenExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client sending expression.
        /// </summary>
        internal static string ClientSendingExpression {
            get {
                return ResourceManager.GetString("ClientSendingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerated.
        /// </summary>
        internal static string Enumerated {
            get {
                return ResourceManager.GetString("Enumerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating.
        /// </summary>
        internal static string Enumerating {
            get {
                return ResourceManager.GetString("Enumerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked.
        /// </summary>
        internal static string Invoked {
            get {
                return ResourceManager.GetString("Invoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking.
        /// </summary>
        internal static string Invoking {
            get {
                return ResourceManager.GetString("Invoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveNext.
        /// </summary>
        internal static string MoveNext {
            get {
                return ResourceManager.GetString("MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnCompleted.
        /// </summary>
        internal static string OnCompleted {
            get {
                return ResourceManager.GetString("OnCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnError.
        /// </summary>
        internal static string OnError {
            get {
                return ResourceManager.GetString("OnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnNext.
        /// </summary>
        internal static string OnNext {
            get {
                return ResourceManager.GetString("OnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server receiving expression.
        /// </summary>
        internal static string ServerReceivingExpression {
            get {
                return ResourceManager.GetString("ServerReceivingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server rewritten expression.
        /// </summary>
        internal static string ServerRewrittenExpression {
            get {
                return ResourceManager.GetString("ServerRewrittenExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed.
        /// </summary>
        internal static string Subscribed {
            get {
                return ResourceManager.GetString("Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing.
        /// </summary>
        internal static string Subscribing {
            get {
                return ResourceManager.GetString("Subscribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribed.
        /// </summary>
        internal static string Unsubscribed {
            get {
                return ResourceManager.GetString("Unsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribing.
        /// </summary>
        internal static string Unsubscribing {
            get {
                return ResourceManager.GetString("Unsubscribing", resourceCulture);
            }
        }
    }
}
